from fpdf import FPDF
import datetime

class HealthReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Virtual Health Assistant - Analysis Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')

def generate_pdf_report(patient_name, analysis, filename):
    """
    Generates a PDF report based on analysis results.
    """
    pdf = HealthReport()
    pdf.add_page()
    pdf.set_font('Arial', '', 12)

    # Patient Info
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, f'Patient: {patient_name}', 0, 1)
    pdf.ln(5)

    # Symptoms
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Symptoms Reported:', 0, 1)
    pdf.set_font('Arial', '', 12)
    symptoms_text = ", ".join(analysis.get('symptoms', ['None']))
    pdf.multi_cell(0, 10, symptoms_text)
    pdf.ln(5)

    # Analysis
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'AI Analysis Result:', 0, 1)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, f'Condition: {analysis.get("condition", "N/A")}', 0, 1)
    pdf.cell(0, 10, f'Severity: {analysis.get("severity", "N/A")}', 0, 1)
    pdf.cell(0, 10, f'Specialty Recommended: {analysis.get("specialty", "N/A")}', 0, 1)
    pdf.ln(5)

    # Remedies
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, 'Suggested Remedies:', 0, 1)
    pdf.set_font('Arial', '', 12)
    for remedy in analysis.get('remedies', []):
        pdf.cell(0, 10, f'- {remedy}', 0, 1)
    
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 10, "Disclaimer: This report is generated by an AI assistant and is not a substitute for professional medical advice.")

    pdf.output(filename)
    return filename
